Add Write implementation for Vec
zakarumych/allocator-api2 pull request #13
Opened 2024-04-11 07:15 UTC by jess-sol

Allows for writing to a Vec which has a custom allocator. This allows crates which implement a Write interface but not allocator-api2 to still write to a Vec with a custom allocator.

2024-04-11 10:26 UTC, zakarumych requested changes
Thank you, this is copy of the standard `Write for Vec`, right?
In this case the only one detail missing is putting it under feature flag.

2024-04-11 14:59 UTC, jess-sol commented on src/stable/vec/mod.rs
> +use std::io;
Oops missed that, added

2024-04-11 15:01 UTC, jess-sol commented
Yep copied it from [latest stable](https://doc.rust-lang.org/stable/src/std/io/impls.rs.html#394-426) :+1:

2024-04-12 11:12 UTC, zakarumych commented
Looks great! Thank you!

2024-04-12 11:12 UTC, merged